version: '2'
services:
  db:
    image: 'postgres:10.5'
    volumes:
      - ~/aabld_data/postgresql:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  app:
    build: .
    image: aabld_app
    command: bundle exec puma -C config/puma.rb
    env_file:
      - config/.env
    volumes:
      - .:/var/www/AABLD
      - ~/backups:/root/backups
    expose:
      - "3000"
    depends_on:
      - db
  web:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    depends_on:
      - app
    ports:
      - "3000:80"
  redis:
    image: redis:latest
  sidekiq:
     image: aabld_app
     command: bundle exec sidekiq -C config/sidekiq.yml
     env_file:
       - config/.env
     depends_on:
       - app
       - redis
     volumes:
       - .:/var/www/AABLD
